builds:
- goos:
  - freebsd
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  - arm
  env:
  - CGO_ENABLED=0
  flags:
  - -a
  - -tags="netgo"
  ldflags:
    - -s -w -extldflags "-static" -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}"

git:
  tags_prefix: "cli/"

release:
  name_template: "v{{.Version}}"

archive:
  name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"

sign:
  artifacts: checksum
