# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/alecthomas/jsonschema"

[[constraint]]
  branch = "master"
  name = "github.com/bmizerany/perks"

[[constraint]]
  branch = "master"
  name = "github.com/dgryski/go-gk"

[[constraint]]
  branch = "master"
  name = "github.com/dgryski/go-lttb"

[[constraint]]
  branch = "master"
  name = "github.com/tsenart/go-tsz"

[[constraint]]
  branch = "master"
  name = "github.com/influxdata/tdigest"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/quantile"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "github.com/shurcooL/vfsgen"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/c2h5oh/datasize"

[[constraint]]
  branch = "master"
  name = "github.com/mailru/easyjson"
