//go:build ignore

// gen-codecs writes bend/tests/{b64,csv,json_str,text}.bend: each case's
// input as hex, and the `#|` lines Go's encoders and decoders give for it
// (encoding/base64, encoding/csv with TrimLeadingSpace, easyjson's jwriter,
// encoding/json). Run from the repo root: go run ./bend/scripts/gen-codecs.go
package main

import (
	"bytes"
	"encoding/base64"
	"encoding/csv"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/mailru/easyjson/jwriter"
)

// show prints bytes visibly: printable ASCII as is (a backslash doubled),
// everything else as \xHH
func show(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '\\':
			b.WriteString(`\\`)
		case c >= 32 && c < 127:
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, `\x%02x`, c)
		}
	}
	return b.String()
}

func hx(s string) string { return `hx("` + hex.EncodeToString([]byte(s)) + `")` }

const helpers = `
def pick(-A: Data, c: Bool, a: A, b: A) -> A:
  match c:
    case True{}:
      a
    case False{}:
      b

def code(c: Char) -> U32:
  Chr{k} = c
  k

def str1(k: U32) -> String:
  SCon{Chr{k}, SNil{}}

def nib(+k: U32) -> U32:
  pick(U32, U32.is_lt(k, 58), (k - 48 : U32), (k - 87 : U32))

# hex text to bytes
def hx(s: String) -> String:
  match s:
    case SNil{}:
      ""
    case SCon{a, r}:
      match r:
        case SNil{}:
          ""
        case SCon{b, r2}:
          SCon{Chr{((nib(code(a)) << 4n) .|. nib(code(b)) : U32)}, hx(r2)}

def hexd(+n: U32) -> String:
  str1(pick(U32, U32.is_lt(n, 10), (48 + n : U32), (87 + n : U32)))

def show1(+k: U32) -> String:
  pick(String, U32.is_eq(k, 92), "\\\\",
  pick(String, Bool.and(U32.is_ge(k, 32), U32.is_lt(k, 127)), str1(k),
    "\\x" ++ hexd((k >> 4n : U32)) ++ hexd((k .&. 15 : U32))))

# bytes shown: printable ASCII as is, a backslash doubled, others as \xHH
def show(s: String) -> String:
  match s:
    case SNil{}:
      ""
    case SCon{c, r}:
      show1(code(c)) ++ show(r)

def some(m: Maybe<&2, String>) -> String:
  match m:
    case None{}:
      "None"
    case Some{s}:
      "Some " ++ show(s)
`

type file struct {
	name, doc, imports, extra string
	body               []string // IO.print lines
	want               []string
}

func (f *file) add(expr, want string) {
	f.body = append(f.body, "    IO.print("+expr+")")
	f.want = append(f.want, "#|"+want)
}

func (f *file) write() {
	var b bytes.Buffer
	b.WriteString("# GENERATED by bend/scripts/gen-codecs.go; do not edit.\n# " + f.doc + "\n")
	b.WriteString("import Base\n" + f.imports + helpers + f.extra)
	b.WriteString("\ndef main() -> IO(Unit):\n  do IO<Unit>:\n")
	b.WriteString(strings.Join(f.body, "\n") + "\n\n")
	b.WriteString(strings.Join(f.want, "\n") + "\n")
	if err := os.WriteFile("bend/tests/"+f.name+".bend", b.Bytes(), 0o644); err != nil {
		panic(err)
	}
}

func b64File() *file {
	f := &file{name: "b64", doc: "B64.encode is base64.StdEncoding; decode accepts only its canonical output.", imports: "import ../lib/b64.bend as B64\n"}
	all := make([]byte, 256)
	for i := range all {
		all[i] = byte(i)
	}
	for _, s := range []string{"", "f", "fo", "foo", "foob", "fooba", "foobar", "\x00", "\xff\xfe\xfd", "\xff\xff", string(all)} {
		enc := base64.StdEncoding.EncodeToString([]byte(s))
		f.add("show(B64.encode("+hx(s)+"))", show(enc))
		f.add("some(B64.decode(B64.encode("+hx(s)+")))", "Some "+show(s))
	}
	strict := base64.StdEncoding.Strict()
	for _, s := range []string{"Zm9vYg==", "Zm9vYmE=", "Zm9vYmFy", "Zm9vYh==", "Zm9vYmF=", "Zm9vYg=", "Zm9vYg", "Zm9v\nYg==", "Zm=vYg==", "Zg==Zg==", "Zm9vYg==Zg==", "Z===", "====", "+/+/", "-_-_", "Zm9vYmFy!", ""} {
		d, err := strict.DecodeString(s)
		want := "None"
		// Go's decoder skips \r and \n; the canonical form has none
		if err == nil && !strings.ContainsAny(s, "\r\n") {
			want = "Some " + show(string(d))
		}
		f.add("some(B64.decode("+hx(s)+"))", want)
	}
	return f
}

const csvExtra = `
def fields(fs: List<&2, String>) -> String:
  match fs:
    case Nil{}:
      ""
    case Con{f, rest}:
      match rest:
        case Nil{}:
          show(f)
        case Con{g, more}:
          show(f) ++ "|" ++ fields(Con{g, more})

def rec(p: List<&2, String> & String) -> String:
  (fs, rest) = p
  "[" ++ fields(fs) ++ "] rest=" ++ show(rest)

def parsed(m: Maybe<&1, List<&2, String> & String>) -> String:
  match m:
    case None{}:
      "None"
    case Some{p}:
      rec(p)
`

func bendList(fs []string) string {
	var xs []string
	for _, s := range fs {
		xs = append(xs, hx(s))
	}
	return "[" + strings.Join(xs, ", ") + "]"
}

func csvFile() *file {
	f := &file{name: "csv", doc: "Csv.field/row are csv.Writer's; parse_row is csv.Reader's Read (TrimLeadingSpace, InputOffset for the rest).", imports: "import ../lib/csv.bend as Csv\n", extra: csvExtra}
	tricky := []string{"a", "b,c", "d\"e", "", " x", "　y", "a\r\nb", "\\.", "\t", "x\r", "\u0085n", " n", " ", " ", " ", " ", " ", " ", "​", "\xe2\x80", "\xc2", "café", "a\nb", "\"", "\r", "\\", "x y"}
	for _, s := range tricky {
		var b bytes.Buffer
		w := csv.NewWriter(&b)
		w.Write([]string{s})
		w.Flush()
		out := b.String()
		f.add("show(Csv.field("+hx(s)+"))", show(strings.TrimSuffix(out, "\n")))
	}
	rows := [][]string{
		{"a", "b,c", "d\"e", "", " x"},
		{"a", "b,c", "d\"e", "", " x", "　y", "a\r\nb"},
		{""}, {"", ""}, {"x"}, {"\\.", "\r", "a\nb"}, {"\"\""},
	}
	for _, r := range rows {
		var b bytes.Buffer
		w := csv.NewWriter(&b)
		w.Write(r)
		w.Flush()
		f.add("show(Csv.row("+bendList(r)+"))", show(b.String()))
	}
	parse := func(s string) {
		r := csv.NewReader(strings.NewReader(s))
		r.TrimLeadingSpace = true
		r.FieldsPerRecord = -1
		rec, err := r.Read()
		want := "None"
		if err == nil {
			var xs []string
			for _, x := range rec {
				xs = append(xs, show(x))
			}
			want = "[" + strings.Join(xs, "|") + "] rest=" + show(s[r.InputOffset():])
		}
		f.add("parsed(Csv.parse_row("+hx(s)+"))", want)
	}
	// every representable row reads back, whatever follows
	for _, r := range [][]string{
		{"a", "b,c", "d\"e", "", " x", "　y", "a\nb"},
		{"", ""}, {"x"}, {"\\.", "\r", "a\nb"}, {"\"\""}, {"x\r"}, {"\r"}, {"\u0085n", " "}, {" "}, {"\t\t"}, {"", "x"},
	} {
		var b bytes.Buffer
		w := csv.NewWriter(&b)
		w.Write(r)
		w.Flush()
		for _, rest := range []string{"", "next,row\n", "\n", "\r\n"} {
			parse(b.String() + rest)
		}
	}
	for _, s := range []string{
		"", "\n", "\r\n", "\r", "\n\r\n\na,b\nc", "a,b", "a,b\r", "a,b\r\n", "a\rb,c\n", "a\r,b\n",
		"  a,  b ,\tc\n", "a, \n", "a,\n", " \n", "　a, b\n", "\xe3\x80a\n", " ,x\n",
		"a\"b\n", "\"a\"b\n", "\"a\" ,b\n", "\"a\n", "\"a\r", "\"a\"\r", "\"a\"\rb\n", "\"a\r\nb\"\r\nz",
		"\"a\rb\"\n", "\"\"\"\"\n", "\"\",\"\"\n", "x,\"y\nz\",w\nrest", " \"q\",r\n", "a,,b\n", ",\n", ",",
		"\"a,b\"", "\"a\"\"\n", "\r\r\n", "a\r\r\n",
	} {
		parse(s)
	}
	return f
}

func jstr(s string) string {
	var w jwriter.Writer
	w.String(s)
	return string(w.Buffer.BuildBytes())
}

const jsonExtra = `
def rd(p: String & String) -> String:
  (s, rest) = p
  show(s) ++ " rest=" ++ show(rest)

def read(m: Maybe<&1, String & String>) -> String:
  match m:
    case None{}:
      "None"
    case Some{p}:
      rd(p)
`

func jsonFile() *file {
	f := &file{name: "json_str", doc: "Json.str is easyjson's jwriter String; read_str is encoding/json's decoding of a string literal.", imports: "import ../lib/json.bend as Json\n", extra: jsonExtra}
	ctl := ""
	for i := 0; i < 32; i++ {
		ctl += string(rune(i))
	}
	strs := []string{"", "abc", "<a href=\"x\">&</a>", ctl, "\x7f", "tab\there\\back/slash", "  ‧‪",
		"café € \U0001f600", "\xff", "a\xc3", "\xc3\x28", "\xe2\x82", "\xed\xa0\x80", "\xf0\x9f\x98", "\xf4\x90\x80\x80",
		"\xc0\xaf", "\xe0\x80\xaf", "\xef\xbf\xbd", "\xf0\x90\x80\x80", "\U0010ffff", "\xe2\x80\xa8x"}
	for _, s := range strs {
		f.add("show(Json.str("+hx(s)+"))", show(jstr(s)))
	}
	read := func(lit, rest string) {
		var out string
		want := "None"
		if err := json.Unmarshal([]byte(lit), &out); err == nil {
			want = show(out) + " rest=" + show(rest)
		}
		f.add("read(Json.read_str("+hx(lit+rest)+"))", want)
	}
	// every valid UTF-8 string reads back, whatever follows
	for _, s := range strs {
		if !isValid(s) {
			continue
		}
		read(jstr(s), ",\"next\":1}")
	}
	for _, lit := range []string{
		`"é€"`, `"😀"`, `"😀x"`, `"\ud83d"`, `"\ude00"`, `"\ud83dx"`, `"\ud83dA"`,
		`"\ud83d😀"`, `"\b\f\n\r\t\/\\\""`, `"\u0000"`, `"\x"`, `"\u12"`, `"\u12g4"`, `"abc`, `"a` + "\n" + `b"`,
		`"a` + "\t" + `"`, `abc`, `""`, `" "`,
	} {
		read(lit, " tail")
	}
	return f
}

func isValid(s string) bool { return strings.ToValidUTF8(s, "\x00BAD") == s }

func textFile() *file {
	f := &file{name: "text", doc: "Text.utf8 turns code points into Go's UTF-8 bytes.", imports: "import ../lib/text.bend as Text\n", extra: `
def cps(ks: List<&2, U32>) -> String:
  match ks:
    case Nil{}:
      ""
    case Con{k, rest}:
      SCon{Chr{k}, cps(rest)}
`}
	for _, s := range []string{"", "abc", "µ", "\u007f\u0080߿ࠀ￿\U00010000\U0010ffff", "café € \U0001f600"} {
		var ks []string
		for _, r := range s {
			ks = append(ks, fmt.Sprint(r))
		}
		f.add("show(Text.utf8(cps(["+strings.Join(ks, ", ")+"])))", show(s))
	}
	return f
}

func main() {
	for _, f := range []*file{b64File(), csvFile(), jsonFile(), textFile()} {
		f.write()
	}
}
