{
 "title": "Vegeta",
 "time": { "from": "2023-07-23T13:28:35.330Z", "to": "2023-07-23T13:33:18.000Z" },
 "panels": [
  {
   "title": "Request Status",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(request_seconds_count{status=~\"2..\"}[1m])/rate(request_seconds_count[1m])",
     "legendFormat": "status {{status}} {{url}}"
    },
    {
     "expr": "rate(request_seconds_count{status=~\"3..\"}[1m])/rate(request_seconds_count[1m])",
     "legendFormat": "status {{status}} {{url}}"
    },
    {
     "expr": "rate(request_seconds_count{status=~\"4..\"}[1m])/rate(request_seconds_count[1m])",
     "legendFormat": "status {{status}} {{url}}"
    },
    {
     "expr": "rate(request_seconds_count{status=~\"5..\"}[1m])/rate(request_seconds_count[1m])",
     "legendFormat": "status {{status}} {{url}}"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(request_seconds_bucket[1m])) by (le, status))",
     "legendFormat": "P50 {{status}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(request_seconds_bucket[1m])) by (le, status))",
     "legendFormat": "P90 {{status}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_seconds_bucket[1m])) by (le, status))",
     "legendFormat": "P99 {{status}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(request_seconds_count[1m])",
     "legendFormat": "throughput {{url}} {{status}}"
    }
   ]
  },
  {
   "title": "Vegeta threads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=\"vegeta\"} ",
     "legendFormat": "Vegeta Go threads"
    },
    {
     "expr": "go_goroutines{job=\"vegeta\"} ",
     "legendFormat": "Vegeta Go routines"
    }
   ]
  },
  {
   "title": "Data throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "rate(request_bytes_in[1m])", "legendFormat": "bytes_out {{url}} {{status}}" },
    { "expr": "rate(request_bytes_out[1m])", "legendFormat": "bytes_out {{url}} {{status}}" }
   ]
  },
  {
   "title": "Vegeta Heap Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"vegeta\"}"
    }
   ]
  }
 ]
}